import js from '@eslint/js';
import globals from 'globals';
import tseslint from 'typescript-eslint';
import reactHooks from 'eslint-plugin-react-hooks';
import reactRefresh from 'eslint-plugin-react-refresh';
import eslintConfigPrettier from 'eslint-config-prettier';

/**
 * ESLint 9 flat config — web app, tests, scripts, contracts, mobile shell.
 * The server has its own config at server/eslint.config.js.
 *
 * Rules that are 'warn' today (explicit any, unused vars, exhaustive-deps)
 * are tracked for tightening in the Phase 3 hardening pass; they must not
 * block CI while the codebase is being brought up to standard.
 */
export default tseslint.config(
  {
    ignores: [
      'node_modules/**',
      'dist/**',
      'coverage/**',
      'playwright-report/**',
      'test-results/**',
      'server/**', // has its own eslint.config.js
      'contracts/index.js', // generated by contracts build tooling
    ],
  },
  {
    files: ['**/*.{ts,tsx}'],
    extends: [js.configs.recommended, ...tseslint.configs.recommended],
    languageOptions: {
      ecmaVersion: 2022,
      globals: { ...globals.browser, ...globals.node },
    },
    plugins: {
      'react-hooks': reactHooks,
      'react-refresh': reactRefresh,
    },
    rules: {
      'react-hooks/rules-of-hooks': 'error',
      'react-hooks/exhaustive-deps': 'warn',
      'react-refresh/only-export-components': ['warn', { allowConstantExport: true }],
      '@typescript-eslint/no-explicit-any': 'warn',
      '@typescript-eslint/no-unused-vars': ['warn', { argsIgnorePattern: '^_' }],
      // Open-09 ratchet (2026-09-15): modules must stay under 700 lines.
      // Existing offenders are tracked in docs/AUDIT_REGISTER.md (Open-09);
      // the warning prevents NEW oversized modules and growing existing ones.
      'max-lines': ['warn', { max: 700, skipBlankLines: true, skipComments: true }],
      // Intentional empty catch blocks (e.g. "non-fatal — keep the stream
      // alive") are a deliberate pattern in this codebase.
      'no-empty': ['error', { allowEmptyCatch: true }],
      // Regex-heavy validation code contains harmless/useful escapes; the
      // rule would risk behavior changes if "fixed" mechanically.
      'no-useless-escape': 'off',
      'no-restricted-syntax': [
        'warn',
        {
          selector: "CallExpression[callee.property.name='getHours']",
          message: 'Use businessHour() or an explicit timezone formatter instead of getHours().',
        },
        {
          selector: "CallExpression[callee.property.name='toLocaleTimeString']",
          message: 'Use formatTime() with the business timezone instead of toLocaleTimeString().',
        },
      ],
    },
  },
  {
    files: ['tests/perf/**/*.{js,mjs}'],
    extends: [js.configs.recommended],
    languageOptions: {
      ecmaVersion: 2022,
      globals: {
        ...globals.node,
        // k6 runtime globals
        __ENV: 'readonly',
        __VU: 'readonly',
      },
    },
    rules: {
      'no-empty': ['error', { allowEmptyCatch: true }],
    },
  },
  {
    files: ['scripts/**/*.{js,mjs,cjs}'],
    extends: [js.configs.recommended],
    languageOptions: {
      ecmaVersion: 2022,
      // Store-automation scripts drive a real browser (Playwright) and
      // reference DOM globals inside page contexts.
      globals: { ...globals.node, ...globals.browser },
    },
    rules: {
      'no-empty': ['error', { allowEmptyCatch: true }],
      'no-unused-vars': ['warn', { argsIgnorePattern: '^_' }],
      // Regex-heavy scripts contain harmless/useful escapes.
      'no-useless-escape': 'off',
    },
  },
  {
    files: ['mobile/**/*.js'],
    extends: [js.configs.recommended],
    languageOptions: {
      ecmaVersion: 2022,
      parserOptions: { ecmaFeatures: { jsx: true } },
      globals: { ...globals.node },
    },
    plugins: {
      'react-hooks': reactHooks,
    },
    rules: {
      'react-hooks/rules-of-hooks': 'error',
      'react-hooks/exhaustive-deps': 'warn',
      'no-empty': ['error', { allowEmptyCatch: true }],
      'no-unused-vars': ['warn', { argsIgnorePattern: '^_' }],
    },
  },
  {
    files: ['**/*.{js,mjs,cjs}'],
    extends: [js.configs.recommended],
    languageOptions: {
      ecmaVersion: 2022,
      globals: { ...globals.node },
    },
    rules: {
      'no-unused-vars': ['warn', { argsIgnorePattern: '^_' }],
      'no-empty': ['error', { allowEmptyCatch: true }],
      // Regex-heavy scripts contain harmless/useful escapes.
      'no-useless-escape': 'off',
    },
  },
  eslintConfigPrettier,
);
