[build]
  builder = "nixpacks"
  buildCommand = "npm run build"

[deploy]
  startCommand = "npm run start"
  preDeployCommand = "cd server && npx prisma db push"
  healthcheckPath = "/api/auth/me"
  restartPolicyMaxRetries = 3

[service]
  port = 5001
